endpoints:
  list_notes:
    url: '/articles'
    method: GET
    db_table: articles
    return: json
    fields: title, url
  add_note:
    url: '/articles'
    method: POST
    db_table: articles
    return: json
    fields: title, url